-- 1.1.15 
SELECT USER_LAT, USER_LON, NETWORK_NAME, MOBILE_NETWORK_TYPE
FROM DATACONNECTION 
WHERE NETWORK_TYPE = 'Wi-Fi' AND NETWORK_NAME = 'CMCC' AND TIME_INDEX_CLIENT BETWEEN 20170101 AND 20180202
AND PING_VALUE = '00000'
LIMIT 10;

-- 网络格式式可选  NETWORK_TYPE
-- 运营商可选    NETWORK_NAME 
-- 日期（范围）  TIME_INDEX_CLIENT
SELECT USER_LAT, USER_LON, NETWORK_NAME, MOBILE_NETWORK_TYPE
FROM DATACONNECTION 
WHERE NETWORK_TYPE = 'Wi-Fi' 
AND NETWORK_NAME = 'CMCC' 
AND TIME_INDEX_CLIENT BETWEEN 20170101 AND 20180202
AND PING_VALUE = '11111'
LIMIT 10;


-- 1.1.16  
SELECT COUNT(*) AS TCOUNT, NETWORK_NAME, NETWORK_TYPE 
FROM DATACONNECTION 
WHERE PING_VALUE = '11111'
GROUP BY NETWORK_NAME, NETWORK_TYPE 
LIMIT 10;

-- 运营商可选
-- 日期（范围）
SELECT COUNT(*) AS TCOUNT, NETWORK_NAME, NETWORK_TYPE 
FROM DATACONNECTION 
WHERE PING_VALUE = '11111'
AND NETWORK_NAME = 'CMCC'
AND TIME_INDEX_CLIENT BETWEEN 20170101 AND 20180202
GROUP BY NETWORK_NAME, NETWORK_TYPE 
LIMIT 10;
-- 数据连接率统计  ： 计算成败数后相除


-- 1.1.28
SELECT COUNT(*) AS COUNT, PROVINCE
FROM NWQUALITY 
GROUP BY PROVINCE
ORDER BY COUNT DESC
LIMIT 10;

-- 运营商可选
-- 日期（范围）
SELECT COUNT(*) AS COUNT, PROVINCE
FROM NWQUALITY
WHERE NWOPERATOR = 'CMCC'
AND DAYTIME BETWEEN 2017010100 AND 2018020200
GROUP BY PROVINCE
ORDER BY COUNT DESC
LIMIT 10;


-- 1.1.29  (结果不同)
SELECT GPSLAT, GPSLON, NWOPERATOR
FROM NWQUALITY 
LIMIT 10;

-- 运营商可选
-- 日期（范围）
SELECT GPSLAT, GPSLON, NWOPERATOR
FROM NWQUALITY 
WHERE NWOPERATOR = 'CUCC'
AND DAYTIME BETWEEN 2017010100 AND 2018020200
LIMIT 10;

