server:
  port: 8082

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:

    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:192.168.10.102,192.168.10.103,192.168.10.104:2181
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

mybatis:
  typeAliasesPackage: com.bigdata.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true