server:
  port: 8081
# spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:192.168.10.102,192.168.10.103,192.168.10.104:2181

mybatis:
  typeAliasesPackage: com.bigdata.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true